from instapy import InstaPy
print("______________________________ SIMPLIKE _________________________________________\n")
print("Developed by Ananda Rauf Maududi\n")
print("Developed date : 24 Juni 2020\n")
print("Simple Auto Like Instagram\n")
print("Tools marketing Instagram\n")
username= input("Masukan username Instagram kamu :\n")
password = input("Masukan password Instagram kamu :\n")
jumlahlike = int(input("Masukan like postingan orang lain :\n"))
jumlahkomen = int(input("Masukan komen postingan orang lain :\n"))
masuk= InstaPy(username,password)
masuk.login()
masuk.like_by_tags(["startupdigital","bisnisdigital"],jumlahlike )
masuk.set_do_comment(True, jumlahkomen)
masuk.set_comments(["Keren kak","Mantap banget infonya","Auto like back kak ^-^"])
print("Like dan komen berhasil ditambahkan")
masuk.end()
